# Generated by Django 4.2.5 on 2023-10-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedaje',
            fields=[
                ('id_hospedaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hospedaje', models.CharField()),
                ('direccion', models.CharField()),
                ('calificacion', models.IntegerField()),
                ('disponible', models.IntegerField(blank=True, null=True)),
                ('id_propietaria', models.IntegerField(blank=True, null=True)),
                ('capacidades', models.TextField()),
                ('nombre_imagen', models.CharField()),
                ('precio_noche', models.IntegerField()),
            ],
        ),
    ]
